In [3]:
import numpy as np

## 1、numpy属性
创建一个numpy数组，并查看它的维度、形状、大小和类型

In [4]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
nature = {'维度':array.ndim, '形状':array.shape, '大小':array.size, '类型':array.dtype}

In [6]:
print(nature)

{'维度': 2, '形状': (3, 3), '大小': 9, '类型': dtype('int32')}


## 2、创建数组
可以通过dtype参数控制数组类型，形如：

In [7]:
a = np.array([1,2,3],dtype=np.float)
print(a.dtype)

float64


通过`np.zeros()`创建一个2行3列的全0矩阵，形如：

In [8]:
zero = np.zeros((2,3)) #生成2行3列全为0的矩阵
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


通过`np.ones()`创建一个3行4列全为1的矩阵，形如：

In [9]:
one = np.ones((3,4)) #生成3行4列全为1的矩阵
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


通过`np.arange()`创建一个等差数组，并通过参数控制起始值、结束值和间距值，形如：

In [10]:
nd1 = np.arange(10)
nd2 = np.arange(4, 12)
nd3 = np.arange(1, 24, 3)
print('nd1:', nd1, nd1.shape, '\nnd2:', nd2, nd2.shape, '\nnd2:', nd3, nd3.shape,)

nd1: [0 1 2 3 4 5 6 7 8 9] (10,) 
nd2: [ 4  5  6  7  8  9 10 11] (8,) 
nd2: [ 1  4  7 10 13 16 19 22] (8,)


通过`np.reshape()`重新定义nd1矩阵的形状为5行2列，形如：

In [11]:
h = nd1.reshape(5,2)#重新定义矩阵的形状
print(h)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 3、numpy矩阵的运算
创建两个numpy矩阵arr1和arr2：

In [12]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[1,1,2], [2,3,3]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 1 2]
 [2 3 3]]


矩阵加法、减法、乘法（点乘）、除法

In [13]:
print(arr1 + arr2)

[[2 3 5]
 [6 8 9]]


In [14]:
print(arr1 - arr2)

[[0 1 1]
 [2 2 3]]


In [15]:
print(arr1 * arr2)

[[ 1  2  6]
 [ 8 15 18]]


In [16]:
print(arr1 / arr2)

[[1.         2.         1.5       ]
 [2.         1.66666667 2.        ]]


矩阵的幂、求商、求余、

In [17]:
print(arr1 ** arr2)

[[  1   2   9]
 [ 16 125 216]]


In [18]:
print(arr1 // arr2)

[[1 2 1]
 [2 1 2]]


In [19]:
print(arr1 % arr2)

[[0 0 1]
 [0 2 0]]


矩阵逻辑运算，判断哪些值大于3

In [20]:
print(arr1>3)

[[False False False]
 [ True  True  True]]


矩阵叉乘，通过`np.dot()`实现，其中arr1为2\*3，arr3为3\*2：

In [21]:
arr3 = np.ones((3,2))
np.dot(arr1,arr3)

array([[ 6.,  6.],
       [15., 15.]])

In [22]:
arr1.dot(arr3)

array([[ 6.,  6.],
       [15., 15.]])

矩阵转置，通过'np.transpose()'或'.T'实现：

In [23]:
print(arr1.T)

[[1 4]
 [2 5]
 [3 6]]


## 4、随机数与矩阵操作
随机数通过`np.random`类下的函数实现，包括纯随机数、正态分布随机数、随机整数等等，例如：

In [24]:
sample1 = np.random.random((3,2)) #生成3行2列从0到1的随机数
sample2 = np.random.normal(size=(1,10)) #生成3行2列符合标准正态分布的随机数
sample3 = np.random.randint(0,10,size=(3,2)) #生成3行2列从0到10的随机整数
print('sample1:',sample1)
print('sample2:',sample2)
print('sample3:',sample3)

sample1: [[0.20851764 0.65305927]
 [0.11839854 0.1234624 ]
 [0.47173529 0.70418576]]
sample2: [[ 0.19993282  0.71223613 -0.25105548  0.22952161 -1.05439482 -1.20315699
   0.7119116  -0.93046797  0.74426924 -1.26174009]]
sample3: [[5 4]
 [1 3]
 [3 4]]


求和，通过`np.sum()`实现，其中`axis`参数可以控制对行或列分别求和，例如：

In [25]:
print(np.sum(sample1)) #对所有元素求和
print(np.sum(sample1,axis=0)) #对所有列求和
print(np.sum(sample1,axis=1)) #对所有行求和

2.2793589060465207
[0.79865147 1.48070743]
[0.86157691 0.24186094 1.17592105]


求最大值、最小值、最大值索引、最小值索引：

In [26]:
print(np.max(sample1)) #求最大值
print(np.argmax(sample1)) #求最大值的索引
print(np.min(sample1)) #求最小值
print(np.argmin(sample1)) #求最小值的索引

0.7041857595234023
5
0.11839853738313877
2


求平均值、中位数：`np.mean()`、`np.median()`

In [27]:
print(np.mean(sample1)) #求平均值
print(np.median(sample1)) #求中位数

0.37989315100775345
0.34012646802999585


排序，通过`np.srot()`函数实现，例如：

In [34]:
sample4 = np.random.randint(0,10,size=(1,10))
print(sample4)
print(np.sort(sample4))

[[7 0 9 1 6 9 0 0 2 4]]
[[0 0 0 1 2 4 6 7 9 9]]


设定最小和最大阈值，小于或大于该数就直接替换：

In [35]:
print(sample4)
print(np.clip(sample4,2,7))#小于2就变成2，大于7就变为7

[[7 0 9 1 6 9 0 0 2 4]]
[[7 2 7 2 6 7 2 2 2 4]]


## 5、numpy的索引

In [36]:
arr1 = np.arange(2,14)
print(arr1)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


按位置进行索引：

In [37]:
print(arr1[2]) #第二个位置的数据
print(arr1[1:4]) #第一到第四个位置的数据
print(arr1[2:-1]) #第二到倒数第一个位置的数据
print(arr1[:5]) #前五个数据
print(arr1[-2:]) #最后两个数据
index = [1,3,3,4,5]
print(arr1[index]) #按照索引列表进行索引

4
[3 4 5]
[ 4  5  6  7  8  9 10 11 12]
[2 3 4 5 6]
[12 13]
[3 5 5 6 7]


二维数组的索引：

In [38]:
arr2 = arr1.reshape(3,4)
print(arr2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [40]:
print(arr2[1]) #索引第一行
print(arr2[1][1]) #第一行第一列的值
print(arr2[1,2]) #第一行和第二列的值
print(arr2[:,2]) #索引第二列

[6 7 8 9]
7
8
[ 4  8 12]


## 6、numpy数组合并

In [41]:
# 创建两个一维数组
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

按垂直方向进行合并：

In [44]:
arr3 = np.vstack((arr1,arr2))#垂直合并
print(arr3, arr3.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


按水平方向进行合并：

In [45]:
arr4 = np.hstack((arr1,arr2))#水平合并
print(arr4, arr4.shape)

[1 2 3 4 5 6] (6,)


按数组维度进行拼接：

In [46]:
arr4 = np.concatenate((arr3,arr3),axis=0)#合并的array维度要相同，array形状要匹配，axis=0纵向合并
print(arr4)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [47]:
arr4 = np.concatenate((arr3,arr3),axis=1)#合并的array维度要相同，array形状要匹配，axis=0纵向合并
print(arr4)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


转置（一维数组转置为本身）：

In [48]:
arr1.T #一维数组转置为本身

array([1, 2, 3])

In [52]:
arr1_1 = arr1[np.newaxis,:] #将一维数组按行方向进行扩维
print(arr1_1.T, arr1_1.T.shape)

[[1]
 [2]
 [3]] (3, 1)


In [51]:
arr1_2 = arr1[:,np.newaxis] #将一维数组按列方向进行扩维
print(arr1_2, arr1_2.shape)

[[1]
 [2]
 [3]] (3, 1)


## 7、numpy数组的分割

In [53]:
arr1 = np.arange(12).reshape((3,4))
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


通过`np.split(data,num,axis)`进行横向分割，分成两份，切割份数必须均匀：

In [55]:
arr2,arr3 = np.split(arr1,2,axis=1)#横向分割，分成2份
print('arr2:', arr2)
print('arr3:', arr3)

arr2: [[0 1]
 [4 5]
 [8 9]]
arr3: [[ 2  3]
 [ 6  7]
 [10 11]]


纵向分割为三份：

In [57]:
arr4,arr5,arr6 = np.split(arr1,3,axis=0)#纵向分割，分成3份
print('arr4:', arr4)
print('arr5:', arr5)
print('arr6:', arr6)

arr4: [[0 1 2 3]]
arr5: [[4 5 6 7]]
arr6: [[ 8  9 10 11]]


通过`np.array_split(data,num,axis)`可以进行不等份分割，如把arr1横向分割为三份：

In [59]:
arr7,arr8,arr9 = np.array_split(arr1,3,axis=1)#横向分割，分成3份，不等分割
print('arr7:', arr7)
print('arr8:', arr8)
print('arr9:', arr9)

arr7: [[0 1]
 [4 5]
 [8 9]]
arr8: [[ 2]
 [ 6]
 [10]]
arr9: [[ 3]
 [ 7]
 [11]]


也可以通过`np.vsplit()`和`np.hsplit`进行纵向和横向的快速分割

In [61]:
arrv1,arrv2,arrv3 = np.vsplit(arr1,3)#纵向分割

arrh1,arrh2 = np.hsplit(arr1,2)#横向分割